.\" Manpage for dkim-gen-keys
.TH DKIM-GEN-KEYS 8 "April 2025" "dkim-gen-keys" "User Commands"
.SH NAME
dkim-gen-keys \- Create PKI DKIM keys for signing emails
.SH SYNOPSIS
.B dkim-gen-keys
[\-b bits] [\-s selector] [\-d domain] [\-h] [\-V]
.SH DESCRIPTION
The
.B dkim-gen-keys
program creates PKI DKIM keys for signing emails. It generates an RSA private key along with the corresponding public key information required for DNS (BIND zone file) entries.

.PP
It accepts several options to control key generation and DNS parameters:

.SH OPTIONS
.TP
.B \-b, --bits <bits>
Key bitlength. Valid values are 512, 1024, or 2048.
Default: 1024.
.TP
.B \-s, --selector <selector>
DNS selector name for this key.
Default: selector.
.TP
.B \-d, --domain <domain>
DNS domain name for this key.
Default: example.com.
.TP
.B \-h, --help
Print help and exit.
.TP
.B \-V, --version
Print version information and exit.
.SH EXAMPLES
To generate a new DKIM key with 1024 bits for the domain "example.com" and selector "selector", run:
.PP
.nf
    dkim-gen-keys -b 1024 -s selector -d example.com
.fi
.SH AUTHOR
Waitman Gobble <waitman@quantificant.com>
.SH LICENSE
Copyright (C) 2025 Waitman Gobble

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, see <https://www.gnu.org/licenses/>.

Contact by email: <waitman@quantificant.com>
<https://quantificant.com/contact>


